#!/bin/bash
set -ex

# installing gnuplot with qt
install gnuplot --with-qt5

# clone and install MOxUnit unit test framework for matlab and octave
git clone https://github.com/MOxUnit/MOxUnit.git
cd MOxUnit
make install
