name: HTML-Preview

on:
  repository_dispatch:
    types: [preview]

jobs:
  report_artifacts:
    runs-on: ubuntu-latest
    name: Report Artifacts
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: rocket
        
      - name: Get preview url using CircleCI REST API
        run: |
          site=`curl -s -H'Circle-Token: ${{ secrets.CIRCLE_CI_ACCESS_TOKEN }}' "https://circleci.com/api/v1.1/project/github/joergbrech/Modellbildung-und-Simulation/latest/artifacts?branch=${{ github.ref }}&filter=successful" | grep '0/html/intro.html' | cut -d \" -f4`
          echo "$site"
          echo "::set-env name=PREVIEW_URL::$site"
          
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            Hello @${{ github.event.client_payload.github.actor }}!
            [Click here to see a preview of the site][1]
            [1]: ${{ env.site }}
