name: html-preview
on: [status]

jobs:
  html-preview:
    runs-on: ubuntu-latest
    name: Create link to html_demo artifact
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.CIRCLECI_TOKEN }}
          artifact-path: 0/html/index.html
          circleci-jobs: html_demo
